### ISSUE TITLE
Material Community Icons have lots of issues

### ISSUE THREAD

**Issue by mikescott** [expo/vector-icons#160]
I've been using this site to find icons: https://icons.expo.fyi/

I have v12.0.3 of expo-vector-icons installed.

**Example 1: Missing Icons**

When searching the website for 'mail' it suggests:

```
<MaterialCommunityIcons name="contact-mail" size={24} color="black" />
```

as an example.

This icon renders as a question mark. It doesn't appear in `build/vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json`

I've found multiple icons suggested by the website that aren't actually present.

See also: #157 

**Example 2: Incorrect Icon**

If you search MaterialCommunityIcons for 'sort' the first icon shows an up/down arrow on the left with the lines on the right sorted in descending order, but using:

```
<MaterialCommunityIcons name="sort" size={24} color="black" />
```

in Expo renders an icon with the lines on the left sorted in ascending order with an up/down arrow on the right.

**Comment by brentvatne** [comment]
what version of the website are you seeing? you should see this:

![Screen Shot 2021-02-25 at 6 50 34 PM](https://user-images.githubusercontent.com/90494/109248274-59c9d300-779a-11eb-9107-89568fee2d54.png)

for 2:

![Screen Shot 2021-02-25 at 6 52 12 PM](https://user-images.githubusercontent.com/90494/109248405-972e6080-779a-11eb-8841-ffb4da462cee.png)

i do not see contact-mail suggested for material community icons on this version. you may need to shift+refresh your page if you had loaded it on a previous version, due to the service worker cache. this shouldn't be a problem in the future because we have disabled the service worker. sorry for the hassle

**Comment by mikescott** [comment]
I see the following:

![Screenshot 2021-04-03 at 14 09 47](https://user-images.githubusercontent.com/5665068/113479312-4b03c980-9486-11eb-9c72-961d9daca267.png)
