### ISSUE TITLE
Warning: Failed prop type: Invalid prop `name` of value `set-meal` supplied to `Icon`,

### ISSUE THREAD

**Issue by AKclown** [expo/vector-icons#164]
Error message：
![image](https://user-images.githubusercontent.com/33648653/111967789-6dffb680-8b33-11eb-9631-741122d228ae.png)

---

Reproduce the code：
When I use the set-meal icon in the page, show me the question mark
![image](https://user-images.githubusercontent.com/33648653/111967893-8b348500-8b33-11eb-9215-2d6547554059.png)

---

Operating environment：
"@expo/vector-icons": "^10.0.0",
"expo": "^38.0.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",

If you let the icon display normally, thanks

**Comment by brentvatne** [comment]
you are seeing this because set-meal is not an icon that is available on MaterialIcons.

the fonts listed on https://icons.expo.fyi/ are for the latest version of @expo/vector-icons, 12.0.4, and you are using version ^10. you can clone this repo and check out version 10 and run the website directory to explore icons, or refer to the allowed fonts from that list you screenshotted
