### ISSUE TITLE
Feather shopping-icon is unexpected

### ISSUE THREAD

**Issue by terrierscript** [expo/vector-icons#213]
Feather icon is all outline style. But current feather shopping-cart icon is solid style.
In react-native-vector-icons has outline shopping-cart but expo/vector-icons got solid

* actual (current expo/vector-icons)
  * https://github.com/expo/vector-icons/blob/master/src/vendor/react-native-vector-icons/Fonts/Feather.ttf
  * ![actual](https://user-images.githubusercontent.com/13282103/163514286-8e008846-f904-47ac-baf2-f08f87ba8a5e.png)
* expected (react-native-vector-icons)
  * ![expected](https://user-images.githubusercontent.com/13282103/163514282-f1c885a4-e046-4802-b392-30abdc9be0c7.png)
  * https://github.com/oblador/react-native-vector-icons/blob/master/Fonts/Feather.ttf

**Comment by gclark-eightfold** [comment]
I was noticing the same thing with missing MaterialCommunityIcons like `office-building-outline`, `database-outline`, `database-arrow-down`, and many more.
Looks like the last time the vendor was updated was on Dec 1, 2020, which would likely be v7.1.0 of [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons/releases) and the fixes for both our icon libraries is included in v9.1.0

I'm sure there's a good reason for this package to clone the vendor rather than making it a dependency, but if it's for Expo Go compatibility, it might be worth trying to simply import react-native-vector-icons directly if you're using a bare or EAS workflow.
Haven't tried that out quite yet, but I'll update my comment if it works w/o issues.

**Comment by gclark-eightfold** [comment]
Update: Turns out the issue I was having with using `react-native-vector-icons` directly was b/c `babel-preset-expo` creates an alias to override the package to use `@expo/vector-icons`.

Instead of falling down that rabbit hole though, I was able to update the `@expo/vector-icons` package to use v9.1.0 in #214 , so hopefully if there's any maintainers that can verify the changes this will be fixed. 😄

**Comment by gclark-eightfold** [comment]
Update: While the PR is being reviewed, I created a gist that might help out patch the package before it's fully updated that works well when I've tested: https://gist.github.com/gclark-eightfold/36dc1e2f560fa6775049d94ae263ad7f
Hope that helps 😄
