### ISSUE TITLE
FontAwesome 5 Pro 

### ISSUE THREAD

**Issue by oskari** [expo/vector-icons#91]
Is FA5Pro supported? From other issues I gathered there is FA5 support now, but I cannot figure a way to use the pro fonts. 

I'm importing vector-icons with ```import { FontAwesome5 } from '@expo/vector-icons'``` and trying to use the "Clipboard-list" icon as "Light" -version with 
```
<FontAwesome5
    name="clipboard-list"
    light
    />
```
but I end up with boxes with crosses inside them, ie. not rendering correctly.

I have the FA5Pro npm package (@fortawesome/fontawesome-pro) installed.

```
Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.5.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```
Vector-icons is installed separately with version ```@expo/vector-icons@10.0.1``` as expo comes with 9 on default.

**Comment by brentvatne** [comment]
FA5 pro isn't supported currently, if you'd like to add support for it you're welcome to open a PR! :) it should be possible to do, we just don't have time right now to work on it

**Comment by mvanroon** [comment]
I took a stab at this: https://github.com/expo/vector-icons/pull/93

**Comment by seguelador** [comment]
I was trying to get Font Awesome 5 using: 
`import { FontAwesome } from '@expo/vector-icons'`
then I saw your code @oskari and it did work. Currently `@expo/vector-icons` supports Font Awesome 5

`import { FontAwesome5 } from '@expo/vector-icons'`

Thanks!

**Comment by alexanderwanyoike** [comment]
Im facing the same problem when using `reactivesearch-native` during build time i get the following error 
```
Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"
```

Thanks to anyone who can help me this is an issue thats taken me 3 days so far

**Comment by umutcanbolat** [comment]
> Im facing the same problem when using `reactivesearch-native` during build time i get the following error
> 
> ```
> Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"
> ```
> 
> Thanks to anyone who can help me this is an issue thats taken me 3 days so far

Hi, this solves the problem until the nex npm install. Run the command in the project directory.

`cp node_modules/\@expo/vector-icons/FontAwesome5.js node_modules/\@expo/vector-icons/FontAwesome5Pro.js`

**Comment by umutcanbolat** [comment]
> Im facing the same problem when using `reactivesearch-native` during build time i get the following error
> 
> ```
> Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"
> ```
> 
> Thanks to anyone who can help me this is an issue thats taken me 3 days so far

Hi! Running the following command in the project directory solves the problem until the next npm install.

`cp node_modules/\@expo/vector-icons/FontAwesome5.js node_modules/\@expo/vector-icons/FontAwesome5Pro.js`

**Comment by amyjchen** [comment]
I've been hitting this issue as well and found that @umutcanbolat's workaround doesn't quite resolve the full issue but I found a terrible workaround that does! Using this for now but might put out a PR later to truly fix since editing your `node_modules` is generally not advised...

This solution assumes that you have the Pro .ttf files in your own repo.
Also note that this solution doesn't generate the corresponding Typescript type files or the `.js.map` file. 

Steps:
1. Write the build/export files yourself.
2. Create a script that copies these into your node modules 
3. Run this script when you need it (perhaps `postinstall`?) 

### Files you'll need
**BuildFontAwesome5Pro.js**
```
import { createFA5iconSet } from './createIconSetFromFontAwesome5';
import glyphMap from './vendor/react-native-vector-icons/glyphmaps/FontAwesome5Pro.json';
import metadata from './vendor/react-native-vector-icons/glyphmaps/FontAwesome5Pro_meta.json';
const fontMap = {
    Regular: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Regular.ttf'),
    Light: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Light.ttf'),
    Solid: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Solid.ttf'),
    Brand: require('./vendor/react-native-vector-icons/Fonts/FontAwesome5_Brands.ttf'),
};
export const FA5Style = {
    regular: 'regular',
    light: 'light',
    solid: 'solid',
    brand: 'brand',
};
const iconSet = createFA5iconSet(glyphMap, metadata, fontMap, true);
export default iconSet;
//# sourceMappingURL=FontAwesome5.js.map
```
Replacing `PATH_TO_YOUR_ASSETS` with your own path to your assets, of course. 

**FontAwesome5Pro.js**
```
import FontAwesome5Pro from './build/FontAwesome5Pro';
export default FontAwesome5Pro;
```

My postinstall script then calls the commands:
```
cp <PATH_TO_YOUR_WORKAROUND_FILES>/FontAwesome5Pro.js node_modules/\@expo/vector-icons/FontAwesome5Pro.js
cp <PATH_TO_YOUR_WORKAROUND_FILES>/BuildFontAwesome5Pro.js node_modules/\@expo/vector-icons/build/FontAwesome5Pro.js
```

Feedback is welcome as I am primarily a FE dev and all I wanted was my pretty `light` icons T.T

**Comment by amyjchen** [comment]
In case anyone else is also hitting this issue, here's a way to get them without having to edit your `node_modules` (heavily based off of this: https://docs.expo.io/guides/icons/). I created another component within my app (aptly called `Icon`). You'll need the FontAwesome5_Pro `glyphMap`, `metadata`, and `.ttf` files, which you should be able to get from the fontawesome-pro package. 

### Steps:
1. In your `components` directory (or whatever you've named it), create an `icons` directory. Add the glyphMap and metadata files to this folder (`FontAwesome5Pro.json` and `FontAwesome5Pro_meta.json`)
2. Create a file in `icons/` called `FontAwesome5Pro.js` and put the following code in it:

```
import { createFA5iconSet } from '@expo/vector-icons/build/createIconSetFromFontAwesome5';
import glyphMap from './FontAwesome5Pro.json';
import metadata from './FontAwesome5Pro_meta.json';

const fontMap = {
  Regular: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Regular.ttf'),
  Light: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Light.ttf'),
  Solid: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Solid.ttf'),
  Brand: require('<PATH_TO_YOUR_ASSETS>/fonts/FontAwesome5_Pro_Brands.ttf'),
};

const FontAwesome5Pro = createFA5iconSet(glyphMap, metadata, fontMap, true);
export default FontAwesome5Pro;
```
where `<PATH_TO_YOUR_ASSETS>` is the path to your assets folder
you may need to use `// eslint-disable-next-line global-require` depending on your eslint settings. 

3. use the Icon component instead of the `@expo/vector-icons` import, for example:

```
import FontAwesome5Pro from '<PATH_TO_YOUR_COMPONENTS>/icons/FontAwesome5Pro';

...

 <FontAwesome5Pro
    name="clipboard-list"
    light
    />
```

This took me quite a bit of digging around and experimenting, so I hope this helps save you some time 🙂

**Comment by mvanroon** [comment]
I recommend using https://github.com/FortAwesome/react-native-fontawesome
