### ISSUE TITLE
Font Awesome 5 icons broken on Android (fix is in react-native-vector-icons 6.4.2)

### ISSUE THREAD

**Issue by clarkcutler** [expo/vector-icons#92]
Version 6.4.2 of `react-native-vector-icons` includes a fix for Font Awesome 5 icons on Android: https://github.com/oblador/react-native-vector-icons/pull/969. Without that fix at least some icons (the "Solid" style icons I think) show up as a box with an X through it.

It wasn't clear to me what version of `react-native-vector-icons` is currently being used / what the process is to upgrade that dependency, but I figured I'd at least file this Issue.

**Comment by brentvatne** [comment]
thanks for pointing this out! at this point we're effectively using a fork of react-native-vector-icons due to https://github.com/expo/vector-icons/pull/84 and https://github.com/expo/vector-icons/pull/83 and https://github.com/expo/vector-icons/pull/82. the quickest way to get this fix in would be to manually port the commit over. ultimately we should probably push the typescript and other changes upstream to react-native-vector-icons so it's easy to stay in sync
